name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Script for pull request event
      uses: actions/github-script@v1.1.0
      if: github.event_name == 'pull_request'
      with:
        script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
        github-token: ${{secrets.GITHUB_TOKEN}}
    - name: GitHub Script for push event
      uses: actions/github-script@v1.1.0
      if: github.event_name == 'push'
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            console.log(context.sha)
            console.log(context.ref)
            console.log(context.actor)
            console.log(context.workflow)
            console.log(context.eventName)
    - name: Commits information
      uses: actions/github-script@v1.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const repository = context.repository
            const sha = context.sha
            console.log(repository)
            console.log(sha)
    - name: Check commit author
      if: github.event_name == 'push'
      run: |
        echo github.event
        echo JSON.parse(github)
