name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Context Content List
      uses: actions/github-script@v1.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context)
    - name: Commits information
      uses: actions/github-script@v1.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const owner = context.repo.owner
          const reponame = context.repo.repo
          console.log(context.sha)

          let results = await Promise.all(
            context.payload.commits.map(commit => {
              let commits_url = `https://api.github.com/repos/${owner}/${reponame}/commits/${commit.id}`
              return github.request(commits_url)
            })
          )
          results.map(result => {
            result.data.files.map(file => console.log(file.filename, file.status))
          })
