name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Context Content List
      uses: actions/github-script@v1.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            console.log(context.sha)
            console.log(context.ref)
            console.log(context.actor)
            console.log(context.workflow)
            console.log(context.eventName)
            console.log(context.payload)
    - name: Commits information
      uses: actions/github-script@v1.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const owner = context.repo.owner
          const reponame = context.repo.repo
          context.payload.commits.map(commit => {
            `https://api.github.com/repos/${owner}/${reponame}/commits/${commit.id}`
            const result = await github.request(commits_url)
            result.data.files.map(file => console.log(file.status, file.name))
          })
