name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Context Content List
      uses: actions/github-script@v1.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log(context)
    - name: Commits information
      uses: actions/github-script@v1.1.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const owner = context.repo.owner
          const reponame = context.repo.repo
          commits_url = `https://api.github.com/repos/${owner}/${reponame}/commits/${context.sha}`
          console.log(context.sha, commits_url)
          context.payload.commits.map(commit => {
            console.log(`commit_id:${commit.id}`)
          })
          const result = await github.request(commits_url)
          result.data.files.map(file => console.log(file.status, file.filename))
