name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: GitHub Script for pull request event
      id: githubscript4pr
      uses: actions/github-script@v1.1.0
      if: ${{ github.event_name == 'pull_request' }}
      with:
        script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
        github-token: ${{secrets.GITHUB_TOKEN}}
    - name: GitHub Script for push event
      id: githubscript4push
      uses: actions/github-script@v1.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        script: |
            const payload = context.payload
            console.log(payload)
            const author = context.payload.commits.author
            console.log(author[0])
        github-token: ${{secrets.GITHUB_TOKEN}}
