name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Script for pull request event
      uses: actions/github-script@v1.1.0
      if: ${{ github.event_name == 'pull_request' }}
      with:
        script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
        github-token: ${{secrets.GITHUB_TOKEN}}
    - name: GitHub Script for push event
      uses: actions/github-script@v1.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const payload = context.payload
            console.log(payload)
    - name: Check commit author
      uses: actions/github-script@v1.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
            const commits = context.payload.commits
            commits.map(commit => {
              console.log(commit)
              console.log(commit.id)
              console.log(commit.message)
              console.log(commit.url)
              console.log(commit.sha)
            })
